"""empty message

Revision ID: 1a7c73395852
Revises: f04acbef1912
Create Date: 2025-04-01 00:10:09.367235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a7c73395852'
down_revision = 'f04acbef1912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('etapa',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('etapa',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
