"""empty message

Revision ID: 540c07746c32
Revises: a536318e9a78
Create Date: 2024-06-27 13:27:05.520620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '540c07746c32'
down_revision = 'a536318e9a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('etiqueta',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('atributos',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('atributos',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('etiqueta',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
