"""empty message

Revision ID: 545ba4aac6ac
Revises: 6a83cd401186
Create Date: 2024-08-15 15:02:50.006412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545ba4aac6ac'
down_revision = '6a83cd401186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
