"""empty message

Revision ID: 59d39d2ba3c1
Revises: 7f1d14d8406d
Create Date: 2024-03-19 09:50:06.265299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59d39d2ba3c1'
down_revision = '7f1d14d8406d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('celular',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
