"""empty message

Revision ID: 6a83cd401186
Revises: ea6045dc085f
Create Date: 2024-08-14 13:53:01.595251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a83cd401186'
down_revision = 'ea6045dc085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.alter_column('video',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('usuario',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('detalle',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('avatar',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('usuario',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('video',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
