"""empty message

Revision ID: 8e74a0046643
Revises: 69bc9fa6635f
Create Date: 2025-04-02 22:53:27.873275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e74a0046643'
down_revision = '69bc9fa6635f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_Flyer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('img_Flyer')

    # ### end Alembic commands ###
