"""empty message

Revision ID: 9f354ace47b7
Revises: df0d0473d2c7
Create Date: 2025-03-31 17:12:16.319174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f354ace47b7'
down_revision = 'df0d0473d2c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
