"""empty message

Revision ID: a536318e9a78
Revises: 855a6b85731b
Create Date: 2024-06-27 13:12:18.875247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a536318e9a78'
down_revision = '855a6b85731b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html5',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('etiqueta', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('atributos', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('date_added', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
