"""empty message

Revision ID: d9211730e8ac
Revises: 8e74a0046643
Create Date: 2025-04-02 23:01:23.304291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9211730e8ac'
down_revision = '8e74a0046643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_Flyer', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('img_Flyer')

    # ### end Alembic commands ###
