"""empty message

Revision ID: df0d0473d2c7
Revises: 8e6cc61aa4aa
Create Date: 2024-08-15 16:44:50.163484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df0d0473d2c7'
down_revision = '8e6cc61aa4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.drop_constraint('multimedia_ibfk_1', type_='foreignkey')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('multimedia_ibfk_1', 'user', ['video_id'], ['id'])

    # ### end Alembic commands ###
