"""empty message

Revision ID: ea6045dc085f
Revises: 8cbeeacbf4b1
Create Date: 2024-08-14 13:30:44.913602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea6045dc085f'
down_revision = '8cbeeacbf4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.String(length=150), nullable=False))
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('multimedia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
