"""empty message

Revision ID: f04acbef1912
Revises: 9f354ace47b7
Create Date: 2025-03-31 17:17:23.400276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f04acbef1912'
down_revision = '9f354ace47b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=mysql.DATETIME(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hora',
               existing_type=sa.Text(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
