"""empty message

Revision ID: fea423a96044
Revises: c1a1dc5da1f3
Create Date: 2025-04-02 23:32:10.056487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fea423a96044'
down_revision = 'c1a1dc5da1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('img_Flyer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_Flyer', mysql.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
